[backdrop]
blur_intensity = 0.1699999962002039
enabled = true
tint_intensity = 0.15999999642372131

[bar.default]
background_opacity = 0.21999999508261681
border = "hover"
end = [
    "group:g1",
    "temp",
    "brightness",
    "audio_visualizer",
    "battery",
    "volume",
    "power_profile",
    "bluetooth",
    "nightlight",
    "notifications",
    "network",
    "session"
]
font_weight = 600
margin_edge = 0
margin_ends = 0
panel_overlap = 0
radius = 0
shadow = false
start = [ "custom_button_2", "workspaces", "clipboard", "control-center", "launcher", "wallpaper", "theme_mode" ]
thickness = 28
widget_spacing = 10

    [[bar.default.capsule_group]]
    fill = "surface"
    id = "g1"
    members = [ "cpu", "ram" ]
    opacity = 0.0
    padding = 6.0

[control_center]
sidebar = "full"
sidebar_section = "full"

[desktop_widgets]
schema_version = 2
widget_order = [ "desktop-widget-0000000000000001" ]

    [desktop_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [desktop_widgets.widget.desktop-widget-0000000000000001]
    box_height = 304.0
    box_width = 640.0
    cx = 960.0
    cy = 932.0
    output = "eDP-1"
    rotation = 0.0
    type = "audio_visualizer"

        [desktop_widgets.widget.desktop-widget-0000000000000001.settings]
        aspect_ratio = 2.1000000000000001
        background = false
        bands = 48.0
        centered = false
        mirrored = true
        show_when_idle = true

[location]
auto_locate = true

[lockscreen_widgets]
enabled = true
schema_version = 2
widget_order = [
    "lockscreen-login-box@eDP-1",
    "lockscreen-widget-0000000000000001",
    "lockscreen-widget-0000000000000002",
    "lockscreen-widget-0000000000000003"
]

    [lockscreen_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [lockscreen_widgets.widget."lockscreen-login-box@eDP-1"]
    box_height = 0.0
    box_width = 0.0
    cx = 960.0
    cy = 957.0
    output = "eDP-1"
    rotation = 0.0
    type = "login_box"

    [lockscreen_widgets.widget.lockscreen-widget-0000000000000001]
    box_height = 96.0
    box_width = 192.0
    cx = 960.0
    cy = 844.0
    output = "eDP-1"
    rotation = -0.0
    type = "clock"

    [lockscreen_widgets.widget.lockscreen-widget-0000000000000002]
    box_height = 96.0
    box_width = 304.0
    cx = 960.0
    cy = 108.0
    output = "eDP-1"
    rotation = 0.0
    type = "weather"

    [lockscreen_widgets.widget.lockscreen-widget-0000000000000003]
    box_height = 32.0
    box_width = 192.0
    cx = 960.0
    cy = 1068.0
    output = "eDP-1"
    rotation = 0.0
    type = "label"

        [lockscreen_widgets.widget.lockscreen-widget-0000000000000003.settings]
        background = true
        background_opacity = 0.13
        background_padding = 9.0
        background_radius = 11.0
        shadow = false
        title = "wer das ließt ist dumm"

[osd]
background_opacity = 0.88999998010694981

[shell]
app_icon_color = "primary"
app_icon_colorize = true
corner_radius_scale = 2.0
font_family = "JetBrainsMono NF ExtraBold"
niri_overview_type_to_launch_enabled = true
settings_show_advanced = true

    [shell.animation]
    speed = 0.90000001341104507

    [shell.panel]
    borders = false
    clipboard_placement = "attached"
    open_near_click_clipboard = true
    open_near_click_control_center = true
    open_near_click_session = true
    open_near_click_wallpaper = true
    shadow = false
    transparency_mode = "soft"

    [shell.screen_corners]
    enabled = true
    size = 21

    [shell.screenshot]
    directory = "/home/cedric/Pictures/Screenshots"

    [[shell.session.actions]]
    action = "lock"
    enabled = true
    variant = "default"

    [[shell.session.actions]]
    action = "logout"
    enabled = true
    variant = "default"

    [[shell.session.actions]]
    action = "lock_and_suspend"
    enabled = true
    variant = "default"

    [[shell.session.actions]]
    action = "reboot"
    enabled = true
    variant = "default"

    [[shell.session.actions]]
    action = "shutdown"
    enabled = true
    variant = "destructive"

    [shell.shadow]
    alpha = 0.0

[theme]
mode = "dark"
source = "wallpaper"
wallpaper_scheme = "vibrant"

    [theme.templates]
    builtin_ids = [ "btop", "gtk3", "gtk4", "kcolorscheme", "kitty", "niri", "qt" ]
    community_ids = [ "pywalfox", "neovim", "obsidian", "vscode", "fuzzel", "discord", "steam", "yazi" ]

[wallpaper]
directory = "/home/cedric/NixOS-Configuration/modules/theming/backgrounds"
edge_smoothness = 0.47999998927116394
fill_mode = "stretch"
transition = [ "disc", "fade", "honeycomb", "stripes", "wipe", "zoom" ]
transition_duration = 100

    [wallpaper.default]
    path = "/home/cedric/NixOS-Configuration/modules/theming/backgrounds/kirby.png"

    [wallpaper.last]
    path = "/home/cedric/NixOS-Configuration/modules/theming/backgrounds/kirby.png"

    [wallpaper.monitors.eDP-1]
    path = "/home/cedric/NixOS-Configuration/modules/theming/backgrounds/kirby.png"

[widget.clipboard]
anchor = true

[widget.clock]
format = "{:%H:%M %d.%m. 20%y}"

[widget.cpu]
label_min_width = 0

[widget.custom_button_2]
command = "kitty --hold fastfetch"
glyph = ""
label = "󱄅"
scale = 1.8500000000000001
type = "custom_button"

[widget.custom_button_3]
glyph = ""
label = "󱄅"
type = "custom_button"

[widget.network]
show_label = false

[widget.network_rx]
label_min_width = 40

[widget.network_tx]
display = "text"
label_min_width = 40

[widget.ram]
label_min_width = 0

[widget.temp]
display = "text"
